name: Docker Image CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bug/**'
      - 'release/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        # Add a new entry to this list for each Dockerfile you want to build.
        # The filename should be relative to the 'containers' folder.
        dockerfile_name:
          - 'runner'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=raw,value=latest
            
      - name: Build and push Docker image for ${{ matrix.dockerfile_name }}
        uses: docker/build-push-action@v5
        with:
          context: ./containers/
          push: true
          # The file input uses the matrix variable - matrix runs are cool
          file: ./containers/${{ matrix.dockerfile_name }}
          tags: |
            ghcr.io/exfactor1337/theworks_${{ matrix.dockerfile_name }}:${{ github.sha }}
            ghcr.io/exfactor1337/theworks_${{ matrix.dockerfile_name }}:latest